# dag config
dag_id: 'action'
schedule: '*/10 * * * *'
max_active_runs: 1
catchup: False

# task config
tasks:
  repository:
    url: "https://api.github.com/repos/{owner}/{repo}/actions/workflows"
    params:
      per_page: 30
      page: 1
  workflow:
    url: "https://api.github.com/repos/{owner}/{repo}/actions/runs"
    params:
      # actor:
      # brnanch:
      # event:
      # status: completed, action_required, cancelled, failure, neutral, skipped, stale, success, timed_out, in_progress, queued, requested, waiting, pending
      per_page: 30
      page: 1
      # created:
      exclude_pull_request: false
      # check_suite_id:
      # head_sha:
  job:
    url: "https://api.github.com/repos/{owner}/{repo}/actions/runs/{run_id}/jobs"
    params:
      # filter: latest, all
      per_page: 30
      page: 1
