# dag config
dag_id: 'detail'
schedule: '*/10 * * * *'
max_active_runs: 1
catchup: False

# task config
tasks:
  issue_and_pr:
    url: "https://api.github.com/search/issues"
    params:
      # q:
      # sort: comments, reactions, reactions-+1, reactions--1, reactions-smile, reactions-thinking_face, reactions-heart, reactions-tada, interactions, created, updated
      per_page: 30
      page: 1