# dag config
dag_id: 'info'
schedule: '*/10 * * * *'
max_active_runs: 1
catchup: False

# task config
tasks:
  release:
    url: "https://api.github.com/repos/{OWNER}/{REPO}/tags"
    params:
      per_page: 30
      page: 1
  project:
    url: "https://api.github.com/repos/{OWNER}/{REPO}/projects"
    params:
      state: "all"
      per_page: 30
      page: 1
  language:
    url: "https://api.github.com/repos/{OWNER}/{REPO}/languages"
  community_profile:
    url: "https://api.github.com/repos/{OWNER}/{REPO}/tags"
    params:
      per_page: 30
      page: 1
  fork:
    url: "https://api.github.com/repos/{owner}/{repo}/forks"
    params:
      # q:
      # sort: comments, reactions, reactions-+1, reactions--1, reactions-smile, reactions-thinking_face, reactions-heart, reactions-tada, interactions, created, updated
      per_page: 30
      page: 1