# dag config
dag_id: 'meta'
schedule: '*/10 * * * *'
max_active_runs: 1
catchup: False

# task config
tasks:
  license:
    url: "https://api.github.com/licenses"
    params:
      per_page: 30
      page: 1